# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProjektIG2
                                 A QGIS plugin
 Wtyczka pozwala obliczyć różnice wysokości pomiędzy punktami oraz pole powierzchni dowolengo poligonu.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-07
        copyright            : (C) 2024 by Bartłomiej Cabaj, Igor Dudek
        email                : bartekc@2003@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ProjektIG2 class from file ProjektIG2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .projekt_2_ig import ProjektIG2
    return ProjektIG2(iface)
