# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projekt_2_ig_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjektIG2DialogBase(object):
    def setupUi(self, ProjektIG2DialogBase):
        ProjektIG2DialogBase.setObjectName("ProjektIG2DialogBase")
        ProjektIG2DialogBase.resize(614, 519)
        self.button_box = QtWidgets.QDialogButtonBox(ProjektIG2DialogBase)
        self.button_box.setGeometry(QtCore.QRect(240, 470, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.pushButton_pole = QtWidgets.QPushButton(ProjektIG2DialogBase)
        self.pushButton_pole.setGeometry(QtCore.QRect(10, 140, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_pole.setFont(font)
        self.pushButton_pole.setObjectName("pushButton_pole")
        self.pushButton_dh = QtWidgets.QPushButton(ProjektIG2DialogBase)
        self.pushButton_dh.setGeometry(QtCore.QRect(10, 90, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_dh.setFont(font)
        self.pushButton_dh.setObjectName("pushButton_dh")
        self.checkBox_ha = QtWidgets.QCheckBox(ProjektIG2DialogBase)
        self.checkBox_ha.setGeometry(QtCore.QRect(200, 190, 81, 20))
        self.checkBox_ha.setObjectName("checkBox_ha")
        self.checkBox_m2 = QtWidgets.QCheckBox(ProjektIG2DialogBase)
        self.checkBox_m2.setGeometry(QtCore.QRect(20, 190, 81, 20))
        self.checkBox_m2.setObjectName("checkBox_m2")
        self.checkBox_ary = QtWidgets.QCheckBox(ProjektIG2DialogBase)
        self.checkBox_ary.setGeometry(QtCore.QRect(100, 190, 81, 20))
        self.checkBox_ary.setObjectName("checkBox_ary")
        self.mMapLayerComboBox = QgsMapLayerComboBox(ProjektIG2DialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(180, 10, 281, 31))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.label_dh_result = QtWidgets.QLabel(ProjektIG2DialogBase)
        self.label_dh_result.setGeometry(QtCore.QRect(270, 90, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dh_result.setFont(font)
        self.label_dh_result.setText("")
        self.label_dh_result.setObjectName("label_dh_result")
        self.label_pole_result = QtWidgets.QLabel(ProjektIG2DialogBase)
        self.label_pole_result.setGeometry(QtCore.QRect(260, 140, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_pole_result.setFont(font)
        self.label_pole_result.setText("")
        self.label_pole_result.setObjectName("label_pole_result")
        self.label_dh_select = QtWidgets.QLabel(ProjektIG2DialogBase)
        self.label_dh_select.setGeometry(QtCore.QRect(20, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dh_select.setFont(font)
        self.label_dh_select.setObjectName("label_dh_select")
        self.pushButton_clear = QtWidgets.QPushButton(ProjektIG2DialogBase)
        self.pushButton_clear.setGeometry(QtCore.QRect(10, 460, 161, 41))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton = QtWidgets.QPushButton(ProjektIG2DialogBase)
        self.pushButton.setGeometry(QtCore.QRect(180, 460, 151, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_wyb_pkt = QtWidgets.QLabel(ProjektIG2DialogBase)
        self.label_wyb_pkt.setGeometry(QtCore.QRect(10, 40, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_wyb_pkt.setFont(font)
        self.label_wyb_pkt.setText("")
        self.label_wyb_pkt.setObjectName("label_wyb_pkt")
        self.mQgsFileWidget = QgsFileWidget(ProjektIG2DialogBase)
        self.mQgsFileWidget.setGeometry(QtCore.QRect(140, 270, 431, 51))
        self.mQgsFileWidget.setObjectName("mQgsFileWidget")
        self.pushButton_punkty = QtWidgets.QPushButton(ProjektIG2DialogBase)
        self.pushButton_punkty.setGeometry(QtCore.QRect(10, 320, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_punkty.setFont(font)
        self.pushButton_punkty.setObjectName("pushButton_punkty")
        self.label = QtWidgets.QLabel(ProjektIG2DialogBase)
        self.label.setGeometry(QtCore.QRect(20, 280, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(ProjektIG2DialogBase)
        self.button_box.accepted.connect(ProjektIG2DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(ProjektIG2DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ProjektIG2DialogBase)

    def retranslateUi(self, ProjektIG2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        ProjektIG2DialogBase.setWindowTitle(_translate("ProjektIG2DialogBase", "Projekt 2 IG"))
        self.pushButton_pole.setText(_translate("ProjektIG2DialogBase", "Oblicz pole"))
        self.pushButton_dh.setText(_translate("ProjektIG2DialogBase", "Oblicz różnicę wysokości"))
        self.checkBox_ha.setText(_translate("ProjektIG2DialogBase", "ha"))
        self.checkBox_m2.setText(_translate("ProjektIG2DialogBase", "m^2"))
        self.checkBox_ary.setText(_translate("ProjektIG2DialogBase", "ary"))
        self.label_dh_select.setText(_translate("ProjektIG2DialogBase", "Wybierz warstwę"))
        self.pushButton_clear.setText(_translate("ProjektIG2DialogBase", "Wyczysc wyniki"))
        self.pushButton.setText(_translate("ProjektIG2DialogBase", "Utworz poligon"))
        self.pushButton_punkty.setText(_translate("ProjektIG2DialogBase", "Wgraj punkty"))
        self.label.setText(_translate("ProjektIG2DialogBase", "Wybierz plik"))
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjektIG2DialogBase = QtWidgets.QDialog()
    ui = Ui_ProjektIG2DialogBase()
    ui.setupUi(ProjektIG2DialogBase)
    ProjektIG2DialogBase.show()
    sys.exit(app.exec_())
