# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProjektIG2Dialog
                                 A QGIS plugin
 Wtyczka pozwala obliczyć różnice wysokości pomiędzy punktami oraz pole powierzchni dowolengo poligonu.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-07
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Bartłomiej Cabaj, Igor Dudek
        email                : bartekc@2003@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets, QtCore
from qgis.core import QgsGeometry




# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'projekt_2_ig_dialog_base.ui'))


class ProjektIG2Dialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ProjektIG2Dialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.pushButton_dh.clicked.connect(self.calculate_dh)
        self.pushButton_pole.clicked.connect(self.oblicz_pole)
        # self.checkBox_m2.stateChanged.connect(self.onCheckBoxChanged)
        # self.checkBox_ary.stateChanged.connect(self.onCheckBoxChanged)
        # self.checkBox_ha.stateChanged.connect(self.onCheckBoxChanged)
    
    def calculate_dh(self):
        selected_layer = self.mMapLayerComboBox.currentLayer()
        features = selected_layer.selectedFeatures()
        if len(features) < 2:
            self.label_dh_result.setText("Wybierz dokładnie dwa punkty!")
        elif len(features) > 3:
            self.label_dh_result.setText("Wybierz dokładnie dwa punkty!")
        else:
            h_1 = float(features[0]['wysokosc'])
            h_2 = float(features[1]['wysokosc'])
            nr1 = features[0]['nr_punktu']
            nr2 = features[1]['nr_punktu']
            dh = h_2 - h_1 
            self.label_dh_result.setText(f'{dh}m')

    def oblicz_pole(self):
        selected_layer = self.mMapLayerComboBox.currentLayer()
        features = selected_layer.selectedFeatures()
        wsp_x = []
        wsp_y = []
        for feature in features:
            geom = feature.geometry()
            point = geom.asPoint()
            wsp_x.append(float(point.x()))
            wsp_y.append(float(point.y()))
            
        if len(wsp_x) < 3:
            self.label_pole_result.setText("Wybierz co najmniej 3 punkty!")
        else:
            coords = list(zip(wsp_x, wsp_y))
                
            n = len(coords)
            suma = 0
            
            for i in range(n):
                x1, y1 = coords[i]
                x2, y2 = coords[(i + 1) % n]
                suma += x1 * y2 - x2 * y1
            
            pole_m2 = 0.5 * abs(suma)
            pole_a = pole_m2 / 100
            pole_ha = pole_m2 / 10000 
            self.label_pole_result.setText(f'{pole_m2} m² ')
        
        # def onCheckBoxChanged(self, state):
        #     if state == QtCore.Qt.Checked:
        #         if self.checkBox_m2.isChecked():
        #             self.label_pole_result.setText(f'{pole_m2} m²')
        #         elif self.checkBox_a.isChecked():
        #             self.label_pole_result.setText(f'{pole_a} a ')
        #         elif self.checkBox_ha.isChecked():
        #             self.label_pole_result.setText(f'{pole_ha} ha')
        

        
        
        
        
        
        
        
        
        